name: Test PyPI install
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * 3'

jobs:
  test-installation:

    name: Test PyPI install (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: [3.9, 3.10, 3.11, 3.12, 3.13]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Setup python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set matplotlib backend (${{ runner.os }})
      if: startsWith(runner.os, 'macOS')
      run: |
        mkdir -p ~/.matplotlib
        echo 'backend: TkAgg' >> ~/.matplotlib/matplotlibrc

    - name: Install package
    # avoid installing pre-releases of non-silicone packages
      run: |
        pip install --upgrade pip wheel
        pip install silicone
        pip install silicone --pre

    - name: Test installation
      run: |
        python scripts/test_install.py
